In [6]:
with open('/content/drive/MyDrive/PK_PY/ReadME.md','w') as f:
    data = f.write('반가워요.')
    print('저장되었습니다.')

저장되었습니다.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 넘파이(numpy)

- ndim:축의 개수
- shape:배열의 차원정보
- size: 배열안에 있는 원소의 총개수
- dtype: 배열원소의 자료형

## 1차원과 속성들

In [17]:
import numpy as np
narry = np.array(range(5))
print(narry,type (narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[4])
print(narry[1:3]) # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
4
[1 2]


In [27]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,'a','b'], dtype='str')
print(narr1,type(narr1))
print(narr1[0],type(narr1[0]))
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] <class 'numpy.ndarray'>
1 <class 'numpy.int64'>
[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' 'a' 'b'] <U1


In [104]:
narr4 = np.zeros((2,2), dtype='int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size ,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size ,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narry.size ,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size ,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size ,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size ,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size ,type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 10 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [47]:
print(list(range(2,10)))
print(np.arange(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


In [43]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype, arr1.shape, arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [57]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원',arr2.ndim,'데이터타입',arr2.dtype, '형태',arr2.shape, arr2.size,'크기',type(arr2),arr2)
print('차원',arr3.ndim,'데이터타입',arr3.dtype, '형태',arr3.shape, arr3.size,'크기',type(arr3),arr3)
print('차원',arr5.ndim,'데이터타입',arr5.dtype, '형태',arr5.shape, arr5.size,'크기',type(arr5),arr5)
print('차원',arr6.ndim,'데이터타입',arr6.dtype, '형태',arr6.shape, arr6.size,'크기',type(arr6),arr6)

차원 2 데이터타입 int64 형태 (3, 3) 9 크기 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 2 데이터타입 int64 형태 (3, 3) 9 크기 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 2 데이터타입 int64 형태 (5, 2) 10 크기 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원 3 데이터타입 int64 형태 (3, 3, 3) 27 크기 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [100]:
t1 = np.arange(1,28).reshape(3,9)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*23)
print(t2)
print("="*23)
print(t3)
print("="*23)
print(t4)
print("="*23)
print(t5)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [93]:
t1 = np.arange(1,11).reshape(5,2)
print(t1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [176]:
print(t1[1][2:5])
print(t4[:3,3:])
print(t4[1:3,4:-1])
print(t4[0][3:])
print(t4[1][3:])
print(t4[2][3:])
print(t4[t4>12])
print([t4>12])
print(t4[t4 % 2 ==0])
print([t4 % 2 ==0])  # 필터역할 가능


[12 13 14]
[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]
[[12 13]
 [19 20]]
[4 5 6 7]
[11 12 13 14]
[18 19 20 21]
[13 14 15 16 17 18 19 20 21]
[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[ 2  4  6  8 10 12 14 16 18 20]
[array([[False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])]


In [178]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가능
np2 =np.array([1,2,3,4,5])
np1 =np.array([6,7,8,9,10])
print("덧셈",np1+np2)
print("뺄셈",np1-np2)
print("곱셈",np1*np2)
print("나눗셈",np1/np2)

덧셈 [ 7  9 11 13 15]
뺄셈 [5 5 5 5 5]
곱셈 [ 6 14 24 36 50]
나눗셈 [6.         3.5        2.66666667 2.25       2.        ]


In [184]:
# 브로드캐스팅
np3 =np1 +10
print(np3)

[16 17 18 19 20]


In [195]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(1,3)
# 스칼라와 연산
print("===스칼라와 연산===")
print(br1)
print("="*23)
print(br1+3)
print("="*23)
print(br1*2)
# 2D 와 1D 의 연산
print("===2D 와 1D 의 연산===")
print("="*23)
print(br1+br2)
print("="*23)
print(br1*br2)

===스칼라와 연산===
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
===2D 와 1D 의 연산===
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [203]:
# flatten 처리
ff=np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(1,9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
